In [1]:
from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

DATA_DIR = Path("../data")
BATTERY_CAPACITY_KWH = 10.0
CHARGE_EFFICIENCY = 0.90
DISCHARGE_EFFICIENCY = 0.90
MAX_CHARGE_RATE_KW = 5.0
MAX_DISCHARGE_RATE_KW = 5.0

In [39]:
# augrid_csv = os.path.join(DATA_DIR, "augrid_solar_hourly.csv")

# augrid_df = pd.read_csv(augrid_csv)
# augrid_df['timestamp'] = pd.to_datetime(
#     augrid_df['timestamp'],
#     format="%Y-%m-%d %H:%M:%S"
# )
# augrid_df['hour'] = augrid_df['timestamp'].dt.hour

FileNotFoundError: [Errno 2] No such file or directory: '../data/augrid_solar_hourly.csv'

In [2]:
augrid_csv_costs = os.path.join(DATA_DIR,'combined/augrid_costs.csv')
augrid_costs_df = pd.read_csv(augrid_csv_costs)

In [3]:
augrid_costs_df.head()

,timestamp,customer_id,generator_capacity_kwp,postcode,cl_kwh,gc_kwh,gg_kwh,hour,import_tariff,export_tariff,total_consumption,cons_min_generation,import_cost_no_solar,import_cost_solar_used_immediate
0,2010-07-01 00:00:00,1,3.78,2076,2.494,0.774,0.0,0,0.2,0.08,3.268,3.268,0.6536,0.6536
1,2010-07-01 00:00:00,3,1.00,2263,4.042,1.340,0.0,0,0.2,0.08,5.382,5.382,1.0764,1.0764
2,2010-07-01 00:00:00,4,1.00,2220,0.000,0.161,0.0,0,0.2,0.08,0.161,0.161,0.0322,0.0322
3,2010-07-01 00:00:00,5,1.00,2261,3.841,0.000,0.0,0,0.2,0.08,3.841,3.841,0.7682,0.7682
4,2010-07-01 00:00:00,6,2.00,2230,0.000,0.085,0.0,0,0.2,0.08,0.085,0.085,0.0170,0.0170

In [8]:
#average yearly cost per customer
augrid_costs_df['timestamp'] = pd.to_datetime(augrid_costs_df['timestamp'])
augrid_costs_df['year'] = augrid_costs_df['timestamp'].dt.year

avg_yearly_cost = (
    augrid_costs_df.groupby(['customer_id', 'year'])['import_cost_no_solar']
    .sum()
    .groupby('customer_id')
    .mean()
)
print(avg_yearly_cost.mean())

#avg solar used immediate
avg_yearly_cost = (
    augrid_costs_df.groupby(['customer_id', 'year'])['import_cost_solar_used_immediate']
    .sum()
    .groupby('customer_id')
    .mean()
)
print(avg_yearly_cost.mean())

1544.9489600501672
1276.595179464883

In [41]:
augrid_costs_df['import_cost_solar_used_immediate'].describe()

count    7.864896e+06
mean     1.941294e-01
std      2.948481e-01
min      0.000000e+00
25%      2.300000e-02
50%      8.232000e-02
75%      2.438800e-01
max      6.067800e+00
Name: import_cost_solar_used_immediate, dtype: float64

In [22]:
augrid_df.head()

,timestamp,customer_id,generator_capacity_kwp,postcode,cl_kwh,gc_kwh,gg_kwh
0,2010-07-01,1,3.78,2076,2.494,0.774,0.0
1,2010-07-01,2,1.62,2259,0.000,0.227,0.0
2,2010-07-01,3,1.00,2263,4.042,1.340,0.0
3,2010-07-01,4,1.00,2220,0.000,0.161,0.0
4,2010-07-01,5,1.00,2261,3.841,0.000,0.0

In [23]:
augrid_df.tail()

,timestamp,customer_id,generator_capacity_kwp,postcode,cl_kwh,gc_kwh,gg_kwh
7889251,2013-06-30 23:00:00,296,1.08,2087,0.000,0.090,0.0
7889252,2013-06-30 23:00:00,297,1.50,2261,1.095,0.348,0.0
7889253,2013-06-30 23:00:00,298,1.02,2216,0.000,0.287,0.0
7889254,2013-06-30 23:00:00,299,1.00,2076,0.000,0.910,0.0
7889255,2013-06-30 23:00:00,300,3.36,2086,2.468,1.029,0.0

In [ ]:
augrid_df_grouped = augrid_df.groupby('customer_id').size().idxmax()

AttributeError: 'numpy.int64' object has no attribute 'head'